version: '3.8'

services:
  service1:
    image: development/flask-app:$TAG
    ports:
      - "5001:5000"

  service2:
    image: development/flask-app:$TAG
    ports:
      - "5002:5000"

  service3:
    image: development/flask-app:$TAG
    ports:
      - "5003:5000"
